### ISSUE TITLE
PostProcessor Script plugin not replacing {source_file_size} with data

### ISSUE THREAD

**Issue by rphwrk** [Unmanic/unmanic-plugins#171] opened 2022-02-01 23:40 UTC
I've written a script to accept the data unmanic once the file is processed. The {source_file_size} variable is not being replaced as expected. Other variables are replaced as expected.

From the debug log:
2022-02-01T23:28:58:INFO:Unmanic.Plugin.postprocessor_script - Execute command on single file '/config/.unmanic/scripts/slack.sh {source_file_size} "/library/..."

Command to execute: /config/.unmanic/scripts/slack.sh
Arguments to pass: {source_file_size} "{output_file_path}"

Plugin version 0.0.3
Unmanic Version: 0.1.4~655b18b
Running inside docker pulled from josh5/unmanic:latest

**Comment by Josh5** [comment] 2022-02-23 08:46
There must be an error being thrown. I cannot reproduce what you are describing.
I configured the script to echo the args to a text file in /tmp and when I read the file {source_file_size} is defiantly being replaced by the file's size in bytes

**Comment by rphwrk** [comment] 2022-02-23 09:58
Thanks for looking into this. I cannot see any errors being thrown:

2022-02-23T09:52:05:DEBUG:Unmanic.Worker-W0 - [FORMATTED] - Executing: ffmpeg -hide_banner -loglevel info -init_hw_device qsv=hw -filter_hw_device hw -i /library/tv/M-A-S-H/season.6/M-A-S-H.s06e21.Temporary.Duty.mkv -strict -2 -max_muxing_queue_size 8198 -vf hwupload=extra_hw_frames=64,format=qsv -map 0:v:0 -map 0:a:0 -map 0:s:0 -c:v:0 hevc_qsv -preset slow -tune film -global_quality 20 -look_ahead 1 -c:a:0 copy -c:s:0 copy -y /tmp/unmanic/unmanic_file_conversion-1643480933.426174/M-A-S-H.s06e21.Temporary.Duty-1643480933.4261396-WORKING-5.mkv

2022-02-23T09:52:17:DEBUG:Unmanic.Plugin.file_size_metrics - Ensuring history database schema exists

2022-02-23T09:52:17:DEBUG:Unmanic.Plugin.file_size_metrics - Ensuring history database schema exists

2022-02-23T09:52:17:INFO:Unmanic.Plugin.postprocessor_script - Execute command on single file 'echo "/library/tv/M-A-S-H/season.6/M-A-S-H.s06e22.Potter's.Retirement.mkv" "{source_file_size}" >> /library/exercise/output.txt'.

2022-02-23T09:52:17:DEBUG:Unmanic.Plugin.postprocessor_script - Executing command: 'echo "/library/tv/M-A-S-H/season.6/M-A-S-H.s06e22.Potter's.Retirement.mkv" "{source_file_size}" >> /library/exercise/output.txt'.

2022-02-23T09:52:17:DEBUG:Unmanic.Plugin.postprocessor_script -

2022-02-23T09:52:17:INFO:Unmanic.PostProcessor - [FORMATTED] - Removing task cache directory '/tmp/unmanic/unmanic_file_conversion-1643480933.45151'

2022-02-23T09:52:17:DEBUG:Unmanic.PostProcessor - [FORMATTED] - Writing task history log.

From my (admittedly novice) investigation, it seems that only the file path is being populated into the data object. I am replacing the original file with the converted file - would that make a difference?

**Comment by Josh5** [comment] 2022-02-27 12:12
Should be fixed if you pull that latest update

**Closed as completed by Josh5** 2022-02-27 12:12 UTC

**Comment by rphwrk** [comment] 2022-03-01 00:10
Confirmed with the latest plugin it now reports the size correctly. Thanks for the patch!
