### ISSUE TITLE
Possible Bug: Reorder Audio by Language

### ISSUE THREAD

**Issue by IamRewt** [Unmanic/unmanic-plugins#107] opened 2021-09-26 22:47 UTC
On some of my files where the audio track is unlabeled, and I'm using the Reorder Audio Tracks by Language plugin, the conversion fails because the audio cannot be mapped.

The log suggests adding a trailing "?" to resolve the problem. 

```
Input #0, mpegts, from '/library/tv/Formula 1 (2021)/Season 2021/Round 15 - Russia.mpg':

   Duration: 03:35:34.02, start: 0.016689, bitrate: 6259 kb/s

   Program 1

     Stream #0:0[0x101]: Audio: aac (HE-AAC) ([15][0][0][0] / 0x000F), 48000 Hz, stereo, fltp, 128 kb/s

     Stream #0:1[0x100]: Video: h264 (High) ([27][0][0][0] / 0x001B), yuv420p(tv, bt709, progressive), 1280x720 [SAR 1:1 DAR 16:9], 59.94 fps, 59.94 tbr, 90k tbn, 119.88 tbc

Stream map '0:s:0' matches no streams.

To ignore this, add a trailing '?' to the map.
```

**Comment by Josh5** [comment] 2021-09-27 00:03
What command is being attempted on your files?

Please post full logs

**Comment by IamRewt** [comment] 2021-09-27 18:20
I had deleted the log after this happened and turned off the plugin to complete the encoding. For some reason, I have not been able to replicate the issue. It is all just working now.

I was using the Reorder audio streams by language plugin, then the Video Encoder H265/HEVC - hevc_nvenc (NVIDIA GPU) Plugin. I did not use any custom ffmpeg options though. 

As of now, all is working as it should though, so I'll update if this occurs again.

**Comment by Josh5** [comment] 2021-09-27 19:34
Ive had something similar happen before a few weeks ago caused by a bug in one of my development builds. That bug should not have made its way to staging or master.

I'll close this issue, but feel free to re-open it if it does happen again.

**Closed as completed by Josh5** 2021-09-27 19:34 UTC
